// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EV.AdminService.API.Models.DataModels;

public partial class AccessLog
{
    public long AccessLogId { get; set; }

    public Guid? OrganizationId { get; set; }

    public Guid? UserId { get; set; }

    public Guid? DatasetVersionId { get; set; }

    public string Action { get; set; }

    public DateTime ActionAt { get; set; }

    public string IpAddress { get; set; }

    public string Details { get; set; }
}