// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EV.AdminService.API.Models.DataModels;

public partial class Analysis
{
    public Guid AnalysisId { get; set; }

    public Guid? DatasetVersionId { get; set; }

    public string Title { get; set; }

    public string Description { get; set; }

    public string ReportUri { get; set; }

    public Guid? CreatedBy { get; set; }

    public DateTime CreatedAt { get; set; }

    public string Visibility { get; set; }

    public virtual DatasetVersion DatasetVersion { get; set; }
}