// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EV.AdminService.API.Models.DataModels;

public partial class ApiKey
{
    public Guid ApiKeyId { get; set; }

    public Guid OrganizationId { get; set; }

    public byte[] KeyHash { get; set; }

    public string Description { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime? ExpiresAt { get; set; }

    public bool Revoked { get; set; }

    public virtual Organization Organization { get; set; }
}