// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EV.AdminService.API.Models.DataModels;

public partial class Consumer
{
    public Guid ConsumerId { get; set; }

    public Guid OrganizationId { get; set; }

    public string ContactEmail { get; set; }

    public virtual Organization Organization { get; set; }
}