// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using EV.AdminService.API.Models.DataModels;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;

namespace EV.AdminService.API.Models.DataModels
{
    public partial interface IEVDataAnalyticsMarketplaceContextProcedures
    {
        Task<int> usp_DistributePaymentAsync(Guid? paymentId, Guid? providerOrgId, decimal? marketplacePercentage, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> usp_PurchaseDatasetAsync(Guid? buyerUserId, Guid? buyerOrgId, Guid? datasetVersionId, decimal? price, string currency, int? accessDays, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<usp_SearchDatasetsResult>> usp_SearchDatasetsAsync(string q, string category, string region, string vehicleType, decimal? minPrice, decimal? maxPrice, int? page, int? pageSize, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
    }
}
