// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EV.AdminService.API.Models.DataModels;

public partial class Provider
{
    public Guid ProviderId { get; set; }

    public Guid OrganizationId { get; set; }

    public string ContactEmail { get; set; }

    public bool Verified { get; set; }

    public DateTime? OnboardedAt { get; set; }

    public virtual ICollection<Dataset> Datasets { get; set; } = new List<Dataset>();

    public virtual Organization Organization { get; set; }
}