// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EV.AdminService.API.Models.DataModels;

public partial class User
{
    public Guid UserId { get; set; }

    public string Email { get; set; }

    public byte[] PasswordHash { get; set; }

    public string DisplayName { get; set; }

    public Guid? OrganizationId { get; set; }

    public DateTime CreatedAt { get; set; }

    public bool IsActive { get; set; }

    public virtual ICollection<Role> Roles { get; set; } = new List<Role>();
}