// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EV.AdminService.API.Models;

public partial class AccessPolicy
{
    public int AccessPolicyId { get; set; }

    public string Name { get; set; }

    public string Description { get; set; }

    public string AllowedUse { get; set; }

    public int? ExpiresInDays { get; set; }

    public DateTime CreatedAt { get; set; }
}