// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EV.AdminService.API.Models;

public partial class DatasetFile
{
    public Guid FileId { get; set; }

    public Guid DatasetVersionId { get; set; }

    public string FileName { get; set; }

    public string FileUri { get; set; }

    public long? FileSizeBytes { get; set; }

    public string Checksum { get; set; }

    public virtual DatasetVersion DatasetVersion { get; set; }
}