// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EV.AdminService.API.Models;

public partial class DataQualityFlag
{
    public long FlagId { get; set; }

    public Guid DatasetVersionId { get; set; }

    public string FlagType { get; set; }

    public string Message { get; set; }

    public string DetailsJson { get; set; }

    public string ProcessedBy { get; set; }

    public DateTime CreatedAt { get; set; }

    public virtual DatasetVersion DatasetVersion { get; set; }
}