// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EV.AdminService.API.Models;

public partial class Payment
{
    public Guid PaymentId { get; set; }

    public Guid? PurchaseId { get; set; }

    public Guid? SubscriptionId { get; set; }

    public decimal Amount { get; set; }

    public string Currency { get; set; }

    public decimal? PaidToProvider { get; set; }

    public decimal? MarketplaceFee { get; set; }

    public DateTime PaidAt { get; set; }

    public string PaymentGateway { get; set; }

    public string TransactionReference { get; set; }

    public virtual Purchase Purchase { get; set; }

    public virtual ICollection<RevenueShare> RevenueShares { get; set; } = new List<RevenueShare>();
}