// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EV.AdminService.API.Models;

public partial class Purchase
{
    public Guid PurchaseId { get; set; }

    public Guid ConsumerOrgId { get; set; }

    public Guid? BuyerUserId { get; set; }

    public Guid DatasetVersionId { get; set; }

    public decimal Price { get; set; }

    public int Quantity { get; set; }

    public string Currency { get; set; }

    public DateTime PurchasedAt { get; set; }

    public DateTime? AccessExpiresAt { get; set; }

    public string TransactionId { get; set; }

    public virtual Organization ConsumerOrg { get; set; }

    public virtual DatasetVersion DatasetVersion { get; set; }

    public virtual ICollection<Payment> Payments { get; set; } = new List<Payment>();
}