// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EV.AdminService.API.Models;

public partial class RevenueShare
{
    public Guid RevenueShareId { get; set; }

    public Guid PaymentId { get; set; }

    public Guid ToOrganizationId { get; set; }

    public decimal Amount { get; set; }

    public string Currency { get; set; }

    public DateTime CreatedAt { get; set; }

    public virtual Payment Payment { get; set; }

    public virtual Organization ToOrganization { get; set; }
}