// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EV.AdminService.API.Models;

public partial class Subscription
{
    public Guid SubscriptionId { get; set; }

    public Guid ConsumerOrgId { get; set; }

    public Guid DatasetId { get; set; }

    public DateTime StartedAt { get; set; }

    public DateTime? ExpiresAt { get; set; }

    public decimal RecurringPrice { get; set; }

    public string Currency { get; set; }

    public bool Active { get; set; }

    public virtual Organization ConsumerOrg { get; set; }

    public virtual Dataset Dataset { get; set; }
}