// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace EV.AdminService.API.Models
{
    public partial class usp_SearchDatasetsResult
    {
        public Guid DatasetId { get; set; }
        [StringLength(500)]
        public string Title { get; set; }
        [StringLength(1000)]
        public string ShortDescription { get; set; }
        [StringLength(100)]
        public string Category { get; set; }
        [StringLength(200)]
        public string Region { get; set; }
        [StringLength(200)]
        public string VehicleTypes { get; set; }
        public Guid? DatasetVersionId { get; set; }
        [StringLength(100)]
        public string VersionLabel { get; set; }
        [StringLength(50)]
        public string FileFormat { get; set; }
        [Column("PricePerDownload", TypeName = "decimal(18,4)")]
        public decimal? PricePerDownload { get; set; }
    }
}
